version: "3"

volumes:
  db:
  pg:
  redis:

services:
  daily-redis:
    image: redis:5.0.10
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 60
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  daily-postgres:
    image: postgres:11.6-alpine
    healthcheck:
      test: pg_isready -U postgres -d $$POSTGRES_DB
      interval: 1s
      timeout: 3s
      retries: 60
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=12345
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  daily-api:
    image: us.gcr.io/daily-ops/daily-api
    depends_on:
      daily-postgres:
        condition: service_healthy
      daily-redis:
        condition: service_healthy
    command:
      ["npm", "run", "start"]
    ports:
      - "5000:5000"
    environment:
      - TYPEORM_HOST=daily-postgres
      - PORT=5000
      - TZ=UTC
      - ACCESS_SECRET='topsecret'
      - DEFAULT_IMAGE_URL=https://res.cloudinary.com/daily-now/image/upload/f_auto/v1/placeholders/1,https://res.cloudinary.com/daily-now/image/upload/f_auto/v1/placeholders/2,https://res.cloudinary.com/daily-now/image/upload/f_auto/v1/placeholders/3,https://res.cloudinary.com/daily-now/image/upload/f_auto/v1/placeholders/4,https://res.cloudinary.com/daily-now/image/upload/f_auto/v1/placeholders/5,https://res.cloudinary.com/daily-now/image/upload/f_auto/v1/placeholders/6,https://res.cloudinary.com/daily-now/image/upload/f_auto/v1/placeholders/7,https://res.cloudinary.com/daily-now/image/upload/f_auto/v1/placeholders/8
      - DEFAULT_IMAGE_RATIO=1
      - DEFAULT_IMAGE_PLACEHOLDER=data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAKAAoDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAABAUGB//EACYQAAIABAQGAwAAAAAAAAAAAAECAAMEBRESE0IGByExQVFScZH/xAAVAQEBAAAAAAAAAAAAAAAAAAABA//EABURAQEAAAAAAAAAAAAAAAAAAAAR/9oADAMBAAIRAxEAPwCgPMKtsdvWjpamiGsuCBVZzn3NmOAB+wYUni23kkz71OM09XObd5jBKufNagklprk4jux9QBqP82/YpQ//2Q==
      - URL_PREFIX=http://localhost:4000
      - COMMENTS_PREFIX=http://localhost:5002
      - FLAGSMITH_KEY=secret
      - REDIS_HOST=daily-redis
      - REDIS_PORT=6379
      - COOKIES_KEY=topsecret
      - JWT_SECRET='|r+.2!!!.Qf_-|63*%.D'
      - JWT_AUDIENCE='Daily Staging'
      - JWT_ISSUER='Daily API Staging'
